/* eslint-disable @typescript-eslint/no-explicit-any */
import { z } from "zod";
const perfumeProduct = "/images/product-perfume.jpg";
const bundleProduct = "/images/product-bundle.jpg";
const brushesProduct = "/images/product-brushes.jpg";
const spongesProduct = "/images/product-sponges.jpg";
const perfumeCategory = "/images/category-perfume.jpg";
const makeupCategory = "/images/category-makeup.jpg";
const accessoriesCategory = "/images/category-accessories.jpg";

export const productCategorySchema = z.enum([
  "perfume",
  "makeup",
  "grooming",
  "bundle",
  "accessories",
]);
export const genderSchema = z.enum(["men", "women", "unisex"]);
export const productSchema = z
  .object({
    id: z.string().min(1),
    name: z.string().min(2),
    slug: z.string().regex(/^[a-z0-9-]+$/),
    description: z.string().min(10),
    price: z.number().positive(),
    salePrice: z.number().positive().optional(),
    gender: genderSchema,
    category: productCategorySchema,
    brand: z.string().min(1),
    sku: z.string().min(3),
    images: z.array(z.string()).min(1),
    fragranceFamily: z.string().optional(),
    topNotes: z.array(z.string()).optional(),
    middleNotes: z.array(z.string()).optional(),
    baseNotes: z.array(z.string()).optional(),
    occasion: z.array(z.string()).optional(),
    longevity: z.string().optional(),
    shade: z.string().optional(),
    finish: z.string().optional(),
    coverage: z.string().optional(),
    skinType: z.string().optional(),
    hairType: z.string().optional(),
    ingredients: z.array(z.string()).optional(),
    stock: z.number().int().nonnegative(),
    rating: z.number().min(0).max(5),
    reviewCount: z.number().int().nonnegative(),
    badge: z.string().optional(),
    tags: z.array(z.string()),
  })
  .refine((product) => !product.salePrice || product.salePrice < product.price, {
    message: "Sale price must be lower than regular price",
    path: ["salePrice"],
  });
export type Gender = z.infer<typeof genderSchema>;
export type ProductCategory = z.infer<typeof productCategorySchema>;
export type Product = z.infer<typeof productSchema>;

const perfume = (
  base: Omit<Product, "category" | "images"> & { gender: Gender; images?: string[] },
): Product => ({
  ...base,
  category: "perfume",
  images: base.images ?? [perfumeProduct],
  tags: base.tags,
});
const makeup = (base: any): Product => ({
  ...base,
  category: "makeup",
  gender: "women",
  images: base.images ?? [makeupCategory],
  tags: base.tags,
});
const grooming = (
  base: Omit<Product, "category" | "images"> & { gender: Gender; images?: string[] },
): Product => ({
  ...base,
  category: "grooming",
  images: base.images ?? [accessoriesCategory],
  tags: base.tags,
});
const bundle = (base: any): Product => ({
  ...base,
  category: "bundle",
  gender: "unisex",
  images: base.images ?? [bundleProduct],
  tags: base.tags,
});

export const products: Product[] = [
  perfume({
    id: "p1",
    name: "Velvet Rose Eau de Parfum",
    slug: "velvet-rose-eau-de-parfum",
    description: "A luminous British floral fragrance wrapped in velvety rose, warm amber, and soft woods.",
    price: 85,
    gender: "women",
    brand: "NOVIXA",
    sku: "NVP-001",
    images: [perfumeProduct, perfumeCategory],
    fragranceFamily: "Floral Amber",
    topNotes: ["Bergamot", "Pear"],
    middleNotes: ["Damask Rose", "Peony"],
    baseNotes: ["Amber", "Sandalwood"],
    occasion: ["Evening", "Signature"],
    longevity: "8–10 hours",
    stock: 18,
    rating: 4.9,
    reviewCount: 128,
    badge: "BEST SELLER",
    tags: ["rose", "floral", "perfume"],
  }),
  perfume({
    id: "p2",
    name: "Noir Élan Eau de Parfum",
    slug: "noir-elan-eau-de-parfum",
    description: "An elegant modern woody scent with bright citrus and a magnetic smoky finish.",
    price: 95,
    gender: "men",
    brand: "NOVIXA",
    sku: "NVP-002",
    images: [perfumeCategory],
    fragranceFamily: "Woody Spicy",
    topNotes: ["Grapefruit", "Cardamom"],
    middleNotes: ["Violet Leaf", "Lavender"],
    baseNotes: ["Vetiver", "Cedar"],
    occasion: ["Work", "Evening"],
    longevity: "8 hours",
    stock: 12,
    rating: 4.8,
    reviewCount: 74,
    tags: ["woody", "men", "perfume"],
  }),
  perfume({
    id: "p3",
    name: "Solaris Homme",
    slug: "solaris-homme",
    description: "Fresh aquatic notes meet warm amber for a confident everyday signature.",
    price: 75,
    gender: "men",
    brand: "NOVIXA",
    sku: "NVP-003",
    fragranceFamily: "Aromatic Aquatic",
    topNotes: ["Mandarin", "Marine Accord"],
    middleNotes: ["Clary Sage"],
    baseNotes: ["Amberwood", "Musk"],
    occasion: ["Daytime"],
    longevity: "6–8 hours",
    stock: 24,
    rating: 4.7,
    reviewCount: 53,
    tags: ["fresh", "men", "perfume"],
  }),
  perfume({
    id: "p4",
    name: "Bloom Silk",
    slug: "bloom-silk",
    description: "A soft, radiant floral veil designed for effortless daily wear.",
    price: 68,
    salePrice: 58,
    gender: "women",
    brand: "NOVIXA",
    sku: "NVP-004",
    images: [perfumeCategory],
    fragranceFamily: "Floral Musk",
    topNotes: ["Litchi", "Freesia"],
    middleNotes: ["Lily", "Rose"],
    baseNotes: ["White Musk"],
    occasion: ["Daytime"],
    longevity: "6 hours",
    stock: 8,
    rating: 4.6,
    reviewCount: 41,
    tags: ["floral", "women", "sale"],
  }),
  perfume({
    id: "p11",
    name: "Cedar Veil",
    slug: "cedar-veil",
    description: "Dry cedar and smooth suede create a quietly confident signature scent.",
    price: 82,
    gender: "men",
    brand: "NOVIXA",
    sku: "NVP-005",
    fragranceFamily: "Woody",
    topNotes: ["Juniper", "Lemon"],
    middleNotes: ["Iris", "Suede"],
    baseNotes: ["Cedar", "Tonka"],
    occasion: ["Work", "Signature"],
    longevity: "8 hours",
    stock: 14,
    rating: 4.7,
    reviewCount: 36,
    tags: ["woody", "men", "cedar"],
  }),
  perfume({
    id: "p12",
    name: "Santal After Dark",
    slug: "santal-after-dark",
    description: "Creamy sandalwood, spice, and warm musk for slow evenings.",
    price: 105,
    gender: "men",
    brand: "NOVIXA",
    sku: "NVP-006",
    fragranceFamily: "Woody Amber",
    topNotes: ["Pink Pepper", "Bergamot"],
    middleNotes: ["Sandalwood", "Nutmeg"],
    baseNotes: ["Vanilla", "Musk"],
    occasion: ["Evening"],
    longevity: "10 hours",
    stock: 9,
    rating: 4.9,
    reviewCount: 58,
    tags: ["sandalwood", "men", "evening"],
  }),
  perfume({
    id: "p27",
    name: "Azure Current",
    slug: "azure-current",
    description: "A crisp marine fragrance brightened with citrus and grounded in driftwood.",
    price: 70,
    gender: "men",
    brand: "NOVIXA",
    sku: "NVP-011",
    fragranceFamily: "Marine Citrus",
    topNotes: ["Lemon", "Sea Salt"],
    middleNotes: ["Geranium", "Lavender"],
    baseNotes: ["Driftwood", "Musk"],
    occasion: ["Daytime", "Travel"],
    longevity: "6–8 hours",
    stock: 19,
    rating: 4.6,
    reviewCount: 27,
    tags: ["marine", "men", "fresh"],
  }),
  perfume({
    id: "p28",
    name: "Obsidian Reserve",
    slug: "obsidian-reserve",
    description: "A deep, polished blend of black pepper, leather, and smoky woods.",
    price: 115,
    gender: "men",
    brand: "NOVIXA",
    sku: "NVP-012",
    fragranceFamily: "Leather Woody",
    topNotes: ["Black Pepper", "Bergamot"],
    middleNotes: ["Leather", "Cypress"],
    baseNotes: ["Oud", "Oakmoss"],
    occasion: ["Evening", "Signature"],
    longevity: "10–12 hours",
    stock: 5,
    rating: 4.9,
    reviewCount: 44,
    badge: "SIGNATURE",
    tags: ["leather", "men", "oud"],
  }),
  perfume({
    id: "p13",
    name: "Petal Smoke",
    slug: "petal-smoke",
    description: "A modern rose with a smoky, mineral edge and an unforgettable drydown.",
    price: 92,
    gender: "women",
    brand: "NOVIXA",
    sku: "NVP-007",
    images: [perfumeCategory],
    fragranceFamily: "Rose Chypre",
    topNotes: ["Blackcurrant", "Pink Pepper"],
    middleNotes: ["Rose", "Incense"],
    baseNotes: ["Patchouli", "Moss"],
    occasion: ["Evening", "Signature"],
    longevity: "9 hours",
    stock: 11,
    rating: 4.8,
    reviewCount: 45,
    tags: ["rose", "women", "smoky"],
  }),
  perfume({
    id: "p14",
    name: "Luna Neroli",
    slug: "luna-neroli",
    description: "Sunlit neroli and white flowers softened by clean musk.",
    price: 72,
    gender: "women",
    brand: "NOVIXA",
    sku: "NVP-008",
    fragranceFamily: "Citrus Floral",
    topNotes: ["Neroli", "Mandarin"],
    middleNotes: ["Orange Blossom", "Jasmine"],
    baseNotes: ["Clean Musk", "Amber"],
    occasion: ["Daytime"],
    longevity: "7 hours",
    stock: 21,
    rating: 4.7,
    reviewCount: 39,
    tags: ["neroli", "women", "fresh"],
  }),
  perfume({
    id: "p15",
    name: "Cashmere Bloom",
    slug: "cashmere-bloom",
    description: "A plush floral musk with a soft cashmere finish.",
    price: 78,
    gender: "women",
    brand: "NOVIXA",
    sku: "NVP-009",
    fragranceFamily: "Floral Musk",
    topNotes: ["Pear", "Aldehydes"],
    middleNotes: ["Iris", "Peony"],
    baseNotes: ["Cashmere Wood", "Musk"],
    occasion: ["Signature"],
    longevity: "8 hours",
    stock: 17,
    rating: 4.8,
    reviewCount: 61,
    tags: ["floral", "women", "musk"],
  }),
  perfume({
    id: "p16",
    name: "Golden Hour",
    slug: "golden-hour",
    description: "A warm glowing blend of saffron, jasmine, and amber woods.",
    price: 98,
    gender: "women",
    brand: "NOVIXA",
    sku: "NVP-010",
    fragranceFamily: "Amber Floral",
    topNotes: ["Saffron", "Citrus"],
    middleNotes: ["Jasmine", "Osmanthus"],
    baseNotes: ["Amberwood", "Musk"],
    occasion: ["Evening"],
    longevity: "10 hours",
    stock: 7,
    rating: 4.9,
    reviewCount: 32,
    badge: "NEW",
    tags: ["amber", "women", "luxury"],
  }),
  makeup({
    id: "p8",
    name: "Matte Muse Lip Colour",
    slug: "matte-muse-lip-colour",
    description: "Comfortable high-pigment colour with a soft matte finish.",
    price: 26,
    brand: "NOVIXA",
    sku: "NVM-001",
    stock: 26,
    rating: 4.8,
    reviewCount: 52,
    shade: "Rosewood",
    finish: "Soft matte",
    coverage: "Full",
    tags: ["lipstick", "makeup", "matte"],
  }),
  makeup({
    id: "p17",
    name: "Cloud Veil Foundation",
    slug: "cloud-veil-foundation",
    description: "Breathable medium-buildable coverage with a soft-focus natural finish.",
    price: 38,
    brand: "NOVIXA",
    sku: "NVM-002",
    stock: 20,
    rating: 4.7,
    reviewCount: 34,
    shade: "Warm Sand",
    finish: "Natural",
    coverage: "Medium-buildable",
    skinType: "All skin types",
    tags: ["foundation", "makeup", "base"],
  }),
  makeup({
    id: "p18",
    name: "Roseglass Blush",
    slug: "roseglass-blush",
    description: "A sheer cream blush that melts into skin for a fresh flush.",
    price: 24,
    brand: "NOVIXA",
    sku: "NVM-003",
    stock: 30,
    rating: 4.8,
    reviewCount: 28,
    shade: "Petal",
    finish: "Dewy",
    coverage: "Sheer-buildable",
    skinType: "Normal to dry",
    tags: ["blush", "makeup", "cream"],
  }),
  makeup({
    id: "p19",
    name: "Inkline Liquid Liner",
    slug: "inkline-liquid-liner",
    description: "A precise, long-wear liquid liner with a deep satin black finish.",
    price: 18,
    brand: "NOVIXA",
    sku: "NVM-004",
    stock: 42,
    rating: 4.6,
    reviewCount: 19,
    shade: "Satin Black",
    finish: "Satin",
    coverage: "Opaque",
    tags: ["liner", "makeup", "eyes"],
  }),
  makeup({
    id: "p20",
    name: "Soft Focus Setting Powder",
    slug: "soft-focus-setting-powder",
    description: "A finely milled powder that sets makeup without flattening the glow.",
    price: 32,
    brand: "NOVIXA",
    sku: "NVM-005",
    stock: 16,
    rating: 4.7,
    reviewCount: 23,
    shade: "Translucent",
    finish: "Soft matte",
    coverage: "Sheer",
    skinType: "All skin types",
    tags: ["powder", "makeup", "setting"],
  }),
  makeup({
    id: "p21",
    name: "Lustre Lip Oil",
    slug: "lustre-lip-oil",
    description: "A cushiony conditioning lip oil with a veil of rose colour.",
    price: 22,
    brand: "NOVIXA",
    sku: "NVM-006",
    stock: 35,
    rating: 4.9,
    reviewCount: 47,
    shade: "Bare Rose",
    finish: "Gloss",
    coverage: "Sheer",
    tags: ["lip oil", "makeup", "gloss"],
  }),
  grooming({
    id: "p9",
    name: "Gentleman Grooming Kit",
    slug: "gentleman-grooming-kit",
    description: "A considered daily ritual with cleanser, moisturiser, and beard oil.",
    price: 55,
    gender: "men",
    brand: "NOVIXA",
    sku: "NVG-001",
    stock: 10,
    rating: 4.6,
    reviewCount: 29,
    ingredients: ["Aloe", "Jojoba", "Squalane"],
    skinType: "Normal to combination",
    hairType: "Beard",
    tags: ["grooming", "men", "kit"],
  }),
  grooming({
    id: "p10",
    name: "Silk Skin Ritual Kit",
    slug: "silk-skin-ritual-kit",
    description: "A calming three-step ritual for hydrated, luminous skin.",
    price: 65,
    gender: "women",
    brand: "NOVIXA",
    sku: "NVG-002",
    images: [makeupCategory],
    stock: 6,
    rating: 4.9,
    reviewCount: 46,
    ingredients: ["Ceramides", "Niacinamide", "Panthenol"],
    skinType: "Dry to sensitive",
    tags: ["skincare", "women", "kit"],
  }),
  grooming({
    id: "p22",
    name: "Atlas Daily Grooming Kit",
    slug: "atlas-daily-grooming-kit",
    description: "A practical three-step grooming ritual for a clean, refreshed start.",
    price: 48,
    gender: "men",
    brand: "NOVIXA",
    sku: "NVG-003",
    stock: 13,
    rating: 4.7,
    reviewCount: 18,
    ingredients: ["Green Tea", "Vitamin E", "Caffeine"],
    skinType: "All skin types",
    hairType: "Short to medium",
    tags: ["grooming", "men", "daily"],
  }),
  grooming({
    id: "p23",
    name: "Rosewater Recovery Kit",
    slug: "rosewater-recovery-kit",
    description: "A gentle recovery ritual for skin that needs calm, comfort, and hydration.",
    price: 58,
    gender: "women",
    brand: "NOVIXA",
    sku: "NVG-004",
    stock: 12,
    rating: 4.8,
    reviewCount: 31,
    ingredients: ["Rosewater", "Oat Extract", "Hyaluronic Acid"],
    skinType: "Sensitive to dry",
    tags: ["skincare", "women", "calming"],
  }),
  bundle({
    id: "p5",
    name: "Complete Glam Bundle",
    slug: "complete-glam-bundle",
    description: "A curated complexion-to-lip edit with everything you need for a polished look.",
    price: 135,
    gender: "women",
    brand: "NOVIXA",
    sku: "NVB-001",
    images: [bundleProduct, makeupCategory],
    stock: 15,
    rating: 5,
    reviewCount: 89,
    badge: "BUNDLE",
    tags: ["makeup", "bundle", "gift"],
  }),
  bundle({
    id: "p24",
    name: "Signature Scent Duo",
    slug: "signature-scent-duo",
    description: "Two complementary NOVIXA fragrances for day and after dark.",
    price: 145,
    gender: "unisex",
    brand: "NOVIXA",
    sku: "NVB-002",
    images: [perfumeProduct, perfumeCategory],
    stock: 9,
    rating: 4.9,
    reviewCount: 22,
    badge: "SAVE 15%",
    tags: ["perfume", "bundle", "gift"],
  }),
  bundle({
    id: "p25",
    name: "The Soft Glam Edit",
    slug: "soft-glam-edit",
    description: "A complete soft-glam colour edit with base, blush, lips, and tools.",
    price: 115,
    gender: "women",
    brand: "NOVIXA",
    sku: "NVB-003",
    images: [bundleProduct, makeupCategory],
    stock: 14,
    rating: 4.8,
    reviewCount: 37,
    badge: "BUNDLE",
    tags: ["makeup", "bundle", "soft glam"],
  }),
  bundle({
    id: "p26",
    name: "Rituals for Two",
    slug: "rituals-for-two",
    description: "A paired fragrance and grooming collection designed for shared rituals.",
    price: 125,
    gender: "unisex",
    brand: "NOVIXA",
    sku: "NVB-004",
    images: [perfumeCategory, accessoriesCategory],
    stock: 8,
    rating: 4.7,
    reviewCount: 16,
    badge: "GIFT SET",
    tags: ["grooming", "perfume", "bundle"],
  }),
  {
    id: "p6",
    name: "Pro Makeup Brush Set",
    slug: "pro-makeup-brush-set",
    description: "Twelve soft-touch professional brushes for seamless blending and detail work.",
    price: 42,
    gender: "unisex",
    category: "accessories",
    brand: "NOVIXA",
    sku: "NVA-001",
    images: [brushesProduct, accessoriesCategory],
    stock: 31,
    rating: 4.8,
    reviewCount: 67,
    tags: ["brushes", "tools", "makeup"],
  },
  {
    id: "p7",
    name: "Blending Sponges — Set of 3",
    slug: "blending-sponges-set",
    description: "Velvety, latex-free sponges that make every base look airbrushed.",
    price: 18,
    gender: "unisex",
    category: "accessories",
    brand: "NOVIXA",
    sku: "NVA-002",
    images: [spongesProduct, accessoriesCategory],
    stock: 44,
    rating: 4.7,
    reviewCount: 38,
    tags: ["sponges", "tools", "makeup"],
  },
  {
    id: "p29",
    name: "Atelier Travel Refill Atomizer",
    slug: "atelier-travel-refill-atomizer",
    description: "Precision-milled 5ml luxury pocket atomizer engineered for fine mist diffusion on the go.",
    price: 22,
    gender: "unisex",
    category: "accessories",
    brand: "NOVIXA",
    sku: "NVA-003",
    images: [accessoriesCategory],
    stock: 50,
    rating: 4.9,
    reviewCount: 42,
    badge: "ESSENTIAL",
    tags: ["atomizer", "accessories", "travel", "perfume"],
  },
];

const ids = new Set<string>();
const slugs = new Set<string>();
products.forEach((product) => {
  productSchema.parse(product);
  if (ids.has(product.id) || slugs.has(product.slug))
    throw new Error(`Duplicate product identity: ${product.id}/${product.slug}`);
  ids.add(product.id);
  slugs.add(product.slug);
});

export const formatPrice = (amount: number) => {
  return new Intl.NumberFormat("en-GB", {
    style: "currency",
    currency: "GBP",
    minimumFractionDigits: Number.isInteger(amount) ? 0 : 2,
    maximumFractionDigits: 2,
  }).format(amount);
};

export const getProduct = (idOrSlug: string) =>
  products.find(
    (product) =>
      product.id === idOrSlug ||
      product.slug === idOrSlug ||
      product.sku === idOrSlug,
  );

export const searchProducts = (query: string) => {
  const q = query.trim().toLowerCase();
  return q
    ? products.filter((product) =>
        [
          product.name,
          product.category,
          product.brand,
          product.fragranceFamily,
          product.shade,
          product.finish,
          product.skinType,
          ...product.tags,
          ...(product.topNotes ?? []),
          ...(product.middleNotes ?? []),
          ...(product.baseNotes ?? []),
        ]
          .filter(Boolean)
          .join(" ")
          .toLowerCase()
          .includes(q),
      )
    : products;
};
